blog_mundial/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from home import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('article/', include('article.urls')),
    path('country/', include('country.urls')),
    path('user/', include('user.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('about/', views.about, name='about'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
     from django.conf.urls.static import static
     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path 
from home import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
]

user/urls.py
from django.urls import path

from user import views


app_name='user'
urlpatterns = [
    path('login', views.login_request, name='user-login'),
    path('logout', views.logout_request, name='user-logout'),
    path('register', views.register, name='user-register'),
    path('register/update', views.user_update, name='user-update'),
    path('avatar/load', views.avatar_load, name='avatar-load'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from user.models import Avatar
# Create your views here.


def index(request):
    avatar_ctx = get_avatar_url_ctx(request)
    context_dict = {**avatar_ctx}
    return render(
        request=request,
        context=context_dict,
        template_name= 'index.html')

def about(request):
    return render(request, 'about.html')


def get_avatar_url_ctx(request):
    avatars = Avatar.objects.filter(user=request.user.id)
    if avatars.exists():
        return {"url": avatars[0].image.url}
    return {}

home/templates/about.html
{% extends "base.html" %}

{% block titulo %} About {% endblock %}


{% block contenido %} 

<h1>Sobre nosotros</h1>

<h3>Creadores del blog: <b>Emanuel Liberal</b> y <b>Camilo Vega</b></h3>

<p>Somos Camilo Vega y Emanuel Liberal, de Uruguay y Argentina respectivamente. Estamos en el curso de Python de la plataforma Coderhouse. Se nos solicito realizar un blog para el proyecto final del curso. 

    "Empecé a estudiar programación porque quería un cambio en mi vida profesional. Siempre me atrajo el mundo de la programación, estudiando ingeniería tuve un acercamiento pero recién ahora me anime a estudiarlo." -Emanuel Liberal.
    
    "Tengo conocimientos de SQL y me gustaría complementarlo con Python y PowerBi. Estudio economía y creo que puedo implementar la programacion a la carrera." - Camilo Vega </p>
{% endblock %}

home/templates/base.html
{% load static %}
<!doctype html> 
<html lang="en">
  <head>
    <title>{% block titulo %} {% endblock %}</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS v5.2.0-beta1 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"  integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

  </head>
  <body>

    <nav class="navbar navbar-expand navbar-light bg-light">
        <div class="nav navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'index' %}">Home </a>
            <a class="nav-item nav-link" href="{% url 'articles' %}">Articulos</a>
            <a class="nav-item nav-link" href="{% url 'countries' %}">Paises</a>
            {% if user.is_authenticated %}
                <a class="btn btn-secondary" href="{% url 'user:user-update' %}">Editar usuario</a>
                <a class="btn btn-primary" href="{% url 'user:user-logout' %}">Cerrar Sesión</a>
                {% else %}
                <a class="btn btn-primary" href="{% url 'user:user-login' %}">Iniciar Sesión</a>
                {% endif %}
        </div>
    </nav>
    
    
    <div class="container">
        <div class="row">
            <div class="col-12">
                {% block contenido %} {% endblock %}
            </div>
        </div>
    </div>


    <!-- FOOTER -->
    <footer class="footer bg-light">
      <div class="container">
          {% if user.is_superuser %}
              <h5><p style="color: rgb(0, 131, 33)" >SuperUser</p></h5>
          {% else %}
              <h5><p style="color: rgb(0, 131, 33)" >Not SuperUser</p></h5>
          {%endif%}
      </div>
      <div class="container">
          <div class="row">
              <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                  <ul class="list-inline mb-2">
                      <li class="list-inline-item"><a href="{% url 'about' %}">About</a></li>
                      <li class="list-inline-item">⋅</li>
                  </ul>
              </div>
              <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
              </div>
          </div>
      </div>
  </footer>
    
    <!-- Bootstrap JavaScript Libraries -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
  </body>
</html>

home/templates/index.html
{% extends "base.html" %}

{% block titulo %} Inicio {% endblock %}

{% load static %}
{% block contenido %} 


{% if user.is_authenticated %}
<div class="text-center">
    <h2>Bienvenido {{ user.username }}</h2>
    <h3><a style="color: rgb(3, 36, 184)" href="{% url 'user:avatar-load' %}">Cambiar Avatar</a></h3>
    <img height="160px" src="{{url}}" alt="">
</div>
{% endif %}


<h1 class="mb-5">Bienvenidos al blog<br> Road to Qatar 2022</h1>

{% endblock %}